version: '3'
services:
  backend:
    build: ./backend
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
